### ISSUE TITLE
is there a way to use the switch_page/page_link components rather than the recommended structure?

### ISSUE THREAD

**Issue by franciscogmm** [gabrieltempass/streamlit-navigation-bar#7]
### Checklist

- [X] I have read the documentation at the [Wiki](https://github.com/gabrieltempass/streamlit-navigation-bar/wiki/API-reference).

### Description

hi! im asking because keeping everything in one page is making my app slower than if it were switching pages. i want to use the nav bar because it's cleaner and looks more professional. thank you.

**Comment by franciscogmm** [comment]
nvm! i did it like this on streamlit 1.34.0

```
    pages = ["Home", "Page 1", "Page 2"]
    page = st_navbar(pages,
                     logo_path=logo_path,
                     styles=styles,
                     options=options,
                     key = 'page_selected'
                     )
    
    if st.session_state.page_selected == "Home":    
        if st.session_state.current_page == 'Home':
            pass
        else:
            st.switch_page('main.py')
        
    elif st.session_state.page_selected == "Page 1":    
        if st.session_state.current_page == 'Page 1':
            pass
        else:
            st.switch_page('pages/page1.py')
            
    elif st.session_state.page_selected == "Page 2":    
        if st.session_state.current_page == 'Page 2':
            pass
        else:
            st.switch_page('pages/page2.py')
```

**Comment by asehmi** [comment]
Instead of this:
```python
        if st.session_state.current_page == 'Home':
            pass
        else:
            st.switch_page('main.py')
```
Do this:
```python
        if st.session_state.current_page != 'Home':
            st.switch_page('main.py')
```

**Comment by gabrieltempass** [comment]
Hi @franciscogmm, thanks for the question! Although you already found the answer, let me still try to contribute to it.

Is there a reason why you are using `st.session_state` to store `page_selected` and `current_page` ? If not, your code can be simplified to something like:

``` python
# main.py

import streamlit as st
from streamlit_navigation_bar import st_navbar

page = st_navbar(["Home", "Page 1", "Page 2"])

if page == "Page 1":
    st.switch_page("pages/page1.py")
if page == "Page 2":
    st.switch_page("pages/page2.py")

# Home content goes here, for example:
st.write("Foo")
```

Then, the script of `page1.py` would look like:

``` python
# pages/page1.py

import streamlit as st
from streamlit_navigation_bar import st_navbar

page = st_navbar(["Home", "Page 1", "Page 2"], selected="Page 1")

if page == "Home":
    st.switch_page("home.py")
if page == "Page 2":
    st.switch_page("pages/page2.py")

# Page 1 content goes here, for example:
st.write("Bar")
```

This approach is demonstrated in the [Streamlit's structure](https://github.com/gabrieltempass/streamlit-navigation-bar/wiki/Multipage#streamlits-structure) page. But be aware, that following your path will cause the navbar to glitch when switching pages. This is less visible in the local mode, and much more when the [app is deployed](https://st-navbar-mpa-st.streamlit.app).
